Ls command
ai-24/ruby-practices pull request #4
Opened 2021-05-15 13:59 UTC by ai-24

lsコマンドを作成しました。レビューよろしくお願いいたします。

2021-05-20 03:42 UTC, u1tnk requested changes

2021-05-20 03:42 UTC, u1tnk commented on 05.ls/ls.rb
> +    extra_list = list.size % 3
こちらに `_size` が無いので分かりづらいかと思いました。

2021-05-20 03:42 UTC, u1tnk commented on 05.ls/ls.rb
> +    length = extra_list != 0 ? list_size + 1 : list_size
豆知識レベルですが、  切り上げをしたそうなので
`(list_size/3.0).ceil ` で出せそうです。

2021-05-20 03:42 UTC, u1tnk commented on 05.ls/ls.rb
> +  def self.number(list)
行列変換を自力でやってるわけですね。偉い 👍 
ただ、名前がnumberだと何をやっているか分からないので、名前は変更しましょう。

自力実装できるのは良いことなんですが、 https://docs.ruby-lang.org/ja/latest/method/Array/i/transpose.html を使うと簡単にはなりますので参考まで。

2021-05-20 03:42 UTC, u1tnk commented on 05.ls/ls.rb
> +class Puts
クラス名は基本的に名詞を付けます。何をやるクラスか明確な名前を付けましょう。

2021-05-20 03:42 UTC, u1tnk commented on 05.ls/ls.rb
> +def option_a
これも option_aのときの current_listsなわけなので、名前を合わせましょう。
あと、 `-a`=`--all` なので プログラム中では allを使うと分かりやすいですね。

2021-05-20 03:42 UTC, u1tnk commented on 05.ls/ls.rb
> +opts = ARGV.getopts('a', 'l', 'r')
この分岐は複雑過ぎるので改善しましょう。

基本的に処理の流れは

1. オプションをチェックして入力を整理
1. ファイル情報を収集
1. 収集した情報を整理
1. 整理した情報を出力

となるはずなので、プログラムもこういう順番で全体の流れば見えるようにしましょう。

各オプションはそれぞれの動作をちょっと変えるだけなので、例えば `-a` なら 「ファイル情報を収集」 するときにオプションがあったら動作を変えるようにすると良いです

2021-05-20 07:32 UTC, ai-24 commented on 05.ls/ls.rb
> +    extra_list = list.size % 3
ありがとうございます！訂正しました！

2021-05-20 07:34 UTC, ai-24 commented on 05.ls/ls.rb
> +    length = extra_list != 0 ? list_size + 1 : list_size
なるほど。
![image](https://user-images.githubusercontent.com/76685187/118937975-1215aa80-b989-11eb-8c1d-c0122d94b661.png)
こちらなぜ2や5より-1の方が大きいと判断されるのでしょうか？

2021-05-20 07:49 UTC, ai-24 commented on 05.ls/ls.rb
> +  def self.number(list)
このメソッド、組み込みであったんですね😵
ここ苦戦していたところなので、悔しいです😅
ありがとうございます！
名前変更しました！

2021-05-20 07:58 UTC, ai-24 commented on 05.ls/ls.rb
> +class Puts
Printにしました！

2021-05-20 08:05 UTC, ai-24 commented on 05.ls/ls.rb
> +def option_a
ありがとうございます！訂正しました！

2021-05-21 06:12 UTC, ai-24 commented on 05.ls/ls.rb
> +    length = extra_list != 0 ? list_size + 1 : list_size
こちら修正してみたのですが、どこに`(list_size/3.0).ceil`を入れると上手くいくのか分かりませんでした。
1の部分に入れてみたのですが、数がうまく取れず、出力されない物があったので、このままにしております。

2021-05-21 06:17 UTC, ai-24 commented on 05.ls/ls.rb
> +opts = ARGV.getopts('a', 'l', 'r')
こちら修正してみました。複雑でないコードという物があまりよく理解できていないので、しっかり修正できているのか、あまり自信はないのですがご確認よろしくお願いいたします。

2021-05-21 12:36 UTC, u1tnk commented on 05.ls/ls.rb
> +    length = extra_list != 0 ? list_size + 1 : list_size
> こちらなぜ2や5より-1の方が大きいと判断されるのでしょうか？

これは 2や5では無く `-1.2`や`-1.5`を切り上げたら -1になるという意味です。

> どこに(list_size/3.0).ceilを入れると上手くいくのか分かりませんでした。

小ネタなので書いちゃうと以下で良いんじゃないかと思いました。
`length = (list_size / 3.0).ceil`

2021-05-21 12:38 UTC, u1tnk commented on 05.ls/ls.rb
> +class Puts
Printも基本的には動詞です。 Printを使うのであれば `Printer` とすると良いですね。
そこらへんはオブジェクト指向プラクティスまでの宿題で大丈夫ですよ。

2021-05-21 12:43 UTC, u1tnk commented on 05.ls/ls.rb
> +opts = ARGV.getopts('a', 'l', 'r')
表現はかなり簡潔になってますね 👍 
ですが、まだちょっと読みづらい状態ですね。

[失なわれた構造化プログラミング、そしてオブジェクト指向へ…](https://u1tnk.github.io/blog/2020/12/17/structured_programming/)

こちら前にLSのレビューを題材に書いた僕のブログで、そのものじゃないんですが、ヒントは十分あると思うので、参考にしてみてください。

2021-05-22 03:07 UTC, ai-24 commented on 05.ls/ls.rb
> +class Puts
動詞と勘違いしていました😨
ありがとうございます！
次回から意識してコードを書いていきたいと思います！

2021-05-24 11:42 UTC, u1tnk requested changes

2021-05-24 11:42 UTC, u1tnk commented on 05.ls/ls.rb
> +lists_result = @option[:a] ? current_lists_all : current_lists
ここの名前が前より良くなりましたね。
ただ、listという単語が配列を表したりする事もあって、あと一息です。

ここは収集されたファイルリストが入るわけなので
`fetched_files` とか `corrected_files` とかかな？

2021-05-24 11:42 UTC, u1tnk commented on 05.ls/ls.rb
> +
この処理全体ですが、 
https://u1tnk.github.io/blog/2020/12/17/structured_programming/

で書いてある事を意識して処理を整理すると以下のような順番でやれば良いかなと思います。
以下の行ごとの処理を意識して分けて、それぞれで結果を変数に保存していけば、optionを見るのはそれぞれ一回で良いし、オプションの数を見る必要も無くなるはずです！

1. 収集されたファイルリスト = 収集する処理(current_list_allとか、今の感じで良いです)
1. ソートされたファイルリスト = 収集されたファイルリストを使ってソート、 `r` オプションときはreverseして無いときはそのまま
1. ソートされたファイルリストを出力、 `l` オプションによって動作を変える

```

2021-05-24 12:16 UTC, ai-24 commented on 05.ls/ls.rb
> +lists_result = @option[:a] ? current_lists_all : current_lists
ありがとうございます！
listは配列を表すのにも使われるのですね！
fetched_filesにしました！！

2021-05-24 12:42 UTC, ai-24 commented on 05.ls/ls.rb
> +
ここの部分分かった気がします！修正してみました！

2021-05-25 01:16 UTC, u1tnk commented on 05.ls/ls.rb
> +if @option[:l] && @option[:r]
惜しいですね。
`option[:r]` の処理は fetched_files_sort で済んでいるのでここで見る必要は無いはずです！

2021-05-25 02:21 UTC, ai-24 commented on 05.ls/ls.rb
> +if @option[:l] && @option[:r]
ここ考えきれていなかったです😅ご指摘ありがとうございます！！

2021-05-25 15:40 UTC, merged